spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      client-id: spring-avro-consumer
      group-id: spring-avro-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
