version: "3"

services:
  zookeeper:
    image: docker.io/debezium/zookeeper:1.8
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: docker.io/debezium/kafka:1.8
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  mysql:
    image: docker.io/debezium/example-mysql:1.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw

  connect:
    image: docker.io/debezium/connect:1.8
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

